*  Codebase and data for: "Variable impacts of forest treatments on mortality and carbon following disturbance"
Authors: Jacob I. Levine, Cedric Zahnd, Libby Blanchard, Jaycie C. Fickle, Tegan Lengyel, Meng Liu, Annapurna C. Post-Leon, Chao Wu, Huiying Xu, Linqing Yu, William R. L. Anderegg

Submitted to /Global Change Biology/ for review on May 21, 2025.

Questions about this repository should be directed to Jacob Levine (@jsilevine; jacob.levine@utah.edu)

**  Overview

This repository contains code and data required to replicate the analyses and figures presented in both the main text and supplement.

*** Data

All data can be found in the =/data= directory, which contains three subdirectories: =/raw_data=, which contains the extracted and cleaned meta-analytic data for each of the three disturbance types (fire, drought, and insects); =/processed_data=, which contains all intermediate data products generated by code in this repository; and =/model_objects=, which contains statistical model fits generated through the analysis, which are used in later scripts (e.g. for figure or table generation).

*** Code

Code used to conduct the statistical analyses can be found in the =/code= directory. There are four main files in this repository: =00_functions.r=, which defines general utility functions; =01_data_cleaning.r=, which processes the raw data into a single clean file used for subsequent analyses; =02_publication_bias.r=, which runs the publication bias analyses; and =03_run_analysis.r=, which will run the full analysis routine, regenerating all intermediate datasets, models, and figures. Scripts to generate the figures in the manuscript are contained in the =/figures= subdirectory, and are labelled according to the figure they correspond to.
